#!/bin/bash

# Script to obtain Let's Encrypt SSL certificate for containers.conflost.com

echo "=== SSL Certificate Setup for containers.conflost.com ==="
echo ""
echo "To get a real SSL certificate from Let's Encrypt, you need to:"
echo ""
echo "1. Make sure port 80 is accessible from the internet"
echo "2. Run certbot with the following command:"
echo ""
echo "   sudo certbot certonly --webroot -w /home/stephen/vps-container-service/public -d containers.conflost.com"
echo ""
echo "3. The certificate files will be created at:"
echo "   - Certificate: /etc/letsencrypt/live/containers.conflost.com/fullchain.pem"
echo "   - Private Key: /etc/letsencrypt/live/containers.conflost.com/privkey.pem"
echo ""
echo "4. Update the container service to use these certificates:"
echo "   - Copy or symlink the certificates to the project directory"
echo "   - Update container-service-v2.js to use the new certificate paths"
echo ""
echo "5. Set up auto-renewal with cron:"
echo "   sudo crontab -e"
echo "   Add: 0 0 1 * * certbot renew --quiet"
echo ""
echo "Alternative: Use Cloudflare Origin Certificates"
echo "1. Go to Cloudflare Dashboard > SSL/TLS > Origin Server"
echo "2. Create an origin certificate for containers.conflost.com"
echo "3. Download the certificate and key"
echo "4. Use these in your service configuration"